### ISSUE TITLE
Consider using GraphicsMagic instead of ImageMagik

### ISSUE THREAD

**Issue by baamenabar** [sadok-f/flyimg#1]
My experience with GraphicsMagic has been far better than with ImageMagik, at least on a windows machine. But I haven't given it too complex tasks.

http://blog.trackduck.com/2014/11/12/imagemagick-vs-graphicsmagick-one-better-process-images-website/

many say in the web, that GraphicsMagis is faster. I'm not sure if the API is the same in every aspect. Again my limited experience says that they use have the same API.

**Comment by sadok-f** [comment]
Thanks Agustin, what I realise from testing both GraphicsMagic and ImageMagik with Mozjpeg is almost the same result always, but didn't make a benchmark yet to see which one is faster.

I would like to make server configurable and we can switch between both library with just change on option in parameters.yml

I'll add the dependencies to Dockerfile to have GraphicsMagic also.

**Comment by baamenabar** [comment]
Cool this way we can switch whenever possible. I was playing with Graphics magic and mozjpeg on the weekend and the performance is fantastic.

**Comment by sadok-f** [comment]
`won't fix`
